title: Daoiist
email: whj.527@gmail.com
description: 分享是一种美德

permalink: /:year/:month/:day/:title.html

github: https://github.com/daoiist

# Build settings
markdown: kramdown
sass:
  style: compressed